const { user, profile } = require("../../models");

exports.addUser = async (req, res) => {
    try{
        const data = req.body;
        const createData = await user.create(data);

        res.send({
            status: "success",
            data: createData,
        });
    }catch(error){
        console.log(error);
        res.send({
            status: "failed",
            message: "server error",
        });
    }
};

exports.getUsers = async (req, res) => {
    try {
      const users = await user.findAll({
        include: {
          model: profile,
          as: "profile",
          attributes: {
            exclude: ["createdAt", "updatedAt", "idUser"],
          },
        },
        attributes: {
          exclude: ["password", "createdAt", "updatedAt"],
        },
      });
  
      res.send({
        status: "success",
        data: {
          users,
        },
      });
    } catch (error) {
      console.log(error);
      res.send({
        status: "failed",
        message: "Server Error",
      });
    }
};

exports.getUser = async (req, res) => {
    try {
      const { id } = req.params;
      const data = await user.findAll({
        where: { id },
        attributes: {
          exclude: ["password", "createdAt", "updatedAt"],
        },
      });
      res.send({
        status: "success",
        data: {
          user: data,
        },
      });
    } catch (error) {
      console.log(error);
      res.send({
        status: "failed",
        message: "server error",
      });
    }
};

exports.updateUser = async (req, res) => {
    try {
      const { id } = req.params;
      await user.update(req.body, {
        where: { id },
      });
      res.send({
        status: "success",
        message: ` update user id: ${id}`,
        data: req.body,
      });
    } catch (error) {
      console.log(error);
      res.send({
        status: "failed",
        message: "server error",
      });
    }
};

exports.deleteUser = async (req, res) => {
    try {
      const { id } = req.params;
      await user.destroy({
        where: { id },
      });
      res.send({
        status: "success",
        message: `delete id user ${id} finished`,
      });
    } catch (error) {
      console.log(error);
      res.send({
        status: "failed",
        message: "server error",
      });
    }
};